url_shortener/my_app/url_shortener/models.py
#modelYetToDeclare!

url_shortener/my_app/__init__.py
from flask import Flask
from my_app.url_shortener.views import url_shortener

app = Flask(__name__)
app.register_blueprint(url_shortener)

url_shortener/my_app/url_shortener/views.py
from flask import abort
from flask import render_template,request
from flask import Blueprint
import pyshorteners
from datetime import date

url_shortener = Blueprint('url_shortener', __name__)

@url_shortener.route('/')
@url_shortener.route('/home')
def home():
	return render_template('home.html')


@url_shortener.route('/shortened_url', methods=['POST'])
def shorten_url():
	link = request.form['link']
	shortner = pyshorteners.Shortener()
	res = shortner.tinyurl.short(link)
	#print(res)
	res = {'short_url_res': res}
	return render_template('result.html', result=res)


@url_shortener.route('/shortened_url_via_api', methods=['POST'])
def shorten_url_via_api():
    today = date.today()
    d2 = today.strftime("%B %d, %Y")

    link = request.args.get('link','')
    shortner = pyshorteners.Shortener()
    res = shortner.tinyurl.short(link)
    #print(res)
    res = { 'result':'Success',
    		'status_code':201,
    		'time':d2,
    		'shortened_url': res}
    return res

url_shortener/my_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>My Short Url!</title>
		<link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
		<link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
	</head>
	<body>
		
		<div class="navbar navbar-inverse navbar-fixed-top header" role="navigation">
		  <a href="{{ url_for('url_shortener.home') }}" style="font-family: monospace;" class="logo">MY_URL_SHORTNER</a>
		  <div class="header-right">
		    <a class="active" style="font-family: monospace; margin-right: 50px	" href="{{ url_for('url_shortener.home') }}">Home</a>
		  </div>
			
		</div>
		<div class="container mid_center text-center" >
			{% block container %}{% endblock %}
		</div>
		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/
		2.0.0/jquery.min.js"></script>
		<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
		<!-- <script src="{{ url_for('static', filename='js/main.js') }}"></script> -->
	</body>
</html>

url_shortener/my_app/templates/home.html
{% extends 'base.html' %}

{% block container %}

	<form action="/shortened_url" method="POST">
	  <div class="form-group">
	    <input type="link" name="link" style="font-family: Verdana; height: 40px; margin-top: 20px" class="form-control text-center" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Paste your link here">
	  </div>
	  <button style="font-family: monospace;" class="btn btn-primary active">Submit</button>
	</form>
{% endblock %}

url_shortener/my_app/templates/result.html
{% extends 'base.html' %}

{% block container %}
	<div>
		<h1 style="font-family: monospace;">Result:: </h1>
		<h1 style="font-family: monospace;" class="label label-success">{{ result['short_url_res'] }}</h1>
	</div>
{% endblock %}